sudo: required

env:
  - TRAVIS_TEST=true

language: elixir 

services:
  - docker

install:
  - git clone --recursive https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - docker-compose up
  - docker ps -a
