sudo: required

env:
  - TRAVIS_TEST=true MIX_ENV=test

language: elixir 
elixir: '1.7.4'

services:
  - docker

cache:
  directories:
    - _build
    - deps

install:
  - git clone --recursive https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script:
  - docker-compose -f docker-compose-test.yml up --exit-code-from phoenix

#after_success:
#  - sudo rm -rf deps
#  - sudo rm -rf _build
#  - mix local.hex --force
#  - mix local.rebar --force
#  - mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez
#  - mix deps.get
#  - mix do compile
#  - mix coveralls.travis
