# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    image: odgaard/phoenix-and-elm_phoenix:latest
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: leiaphx_dev 
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: postgres_db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      # The db container needs to be started before we start this container
      - postgres_db 
  postgres_db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leiaphx_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
